version: "3.7"

services:
  db:
    container_name: video_converter_db
    image: postgres:10.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: video_converter_backend
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: docker/django/start.sh
    volumes:
      - .:/app
      - staticfiles:/opt/video_converter/staticfiles
      - media:/opt/video_converter/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - celery
    depends_on:
      - db
  redis:
    container_name: 'redis'
    image: redis:5.0.4
    restart: always
    expose:
      - "6379"
  celery:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - db
      - redis
    depends_on:
      - redis



volumes:
  postgres_data:
  staticfiles:
  media:
  redisdata: